# Конфиг для разработки
version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ../backend/.env
    volumes:
      - static_value:/app/django/static/
      - media_value:/app/django/media/

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/django/static/
      - media_value:/var/html/django/media/

    depends_on:
      - frontend

volumes:
  db:
  static_value:
  media_value: